"""add payroll parameter tables

Revision ID: 0615b6b03fc4
Revises: 3aff068a92d3
Create Date: 2026-06-07 13:40:59.624200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0615b6b03fc4'
down_revision: Union[str, Sequence[str], None] = '3aff068a92d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_income_tax_brackets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bracket_order', sa.Integer(), nullable=False),
    sa.Column('cumulative_min', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cumulative_max', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_minimum_wage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('period_code', sa.String(length=20), nullable=False),
    sa.Column('gross_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_daily', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_rates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rate_key', sa.String(length=50), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_rates')
    op.drop_table('payroll_minimum_wage')
    op.drop_table('payroll_income_tax_brackets')
    # ### end Alembic commands ###
