"""add company_type and oversight_links

Revision ID: 7191c2ecbbdb
Revises: ba1cd2ffa7fe
Create Date: 2026-06-08 08:05:24.371441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7191c2ecbbdb'
down_revision: Union[str, Sequence[str], None] = 'ba1cd2ffa7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oversight_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_company_id', sa.String(), nullable=False),
    sa.Column('sub_company_id', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['sub_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Mevcut company'lere "standalone" ata (NOT NULL ihlalini önler), sonra default'u kaldır.
    op.add_column('companies', sa.Column('company_type', sa.String(length=20), nullable=False, server_default="standalone"))
    op.alter_column('companies', 'company_type', server_default=None)    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'company_type')
    op.drop_table('oversight_links')
    # ### end Alembic commands ###
