"""finance soft delete and audit log

Revision ID: 90f00e711df1
Revises: eb4e7672ab49
Create Date: 2026-06-13 09:23:38.829422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '90f00e711df1'
down_revision: Union[str, Sequence[str], None] = 'eb4e7672ab49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    financeauditaction = postgresql.ENUM('created', 'updated', 'deleted', name='financeauditaction')
    financeauditaction.create(op.get_bind(), checkfirst=True)
    op.create_table('finance_audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('entry_id', sa.String(), nullable=True),
    sa.Column('action', postgresql.ENUM('created', 'updated', 'deleted', name='financeauditaction', create_type=False), nullable=False),
    sa.Column('kind', postgresql.ENUM('income', 'expense', name='financekind', create_type=False), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['finance_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('finance_entries', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('finance_entries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('finance_entries', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('finance_entries', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'finance_entries', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_entries', type_='foreignkey')
    op.drop_column('finance_entries', 'updated_at')
    op.drop_column('finance_entries', 'deleted_by')
    op.drop_column('finance_entries', 'deleted_at')
    op.drop_column('finance_entries', 'is_deleted')
    op.drop_table('finance_audit_log')
    # ### end Alembic commands ###
