"""add shift_templates table

Revision ID: 96f09c525cd7
Revises: 90f00e711df1
Create Date: 2026-06-15 07:28:53.979004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f09c525cd7'
down_revision: Union[str, Sequence[str], None] = '90f00e711df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_label', sa.String(length=5), nullable=False),
    sa.Column('end_label', sa.String(length=5), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_templates')
    # ### end Alembic commands ###
