"""add payslips table

Revision ID: ba1cd2ffa7fe
Revises: 0615b6b03fc4
Create Date: 2026-06-07 16:23:59.342560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1cd2ffa7fe'
down_revision: Union[str, Sequence[str], None] = '0615b6b03fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payslips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('sgk_days', sa.Integer(), nullable=False),
    sa.Column('full_monthly_gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgk_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgk_employee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unemployment_employee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('income_tax_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cumulative_base_before', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cumulative_base_after', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('income_tax_gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('income_tax_exemption', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('income_tax_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stamp_tax_gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stamp_tax_exemption', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stamp_tax_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgk_employer', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unemployment_employer', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('employer_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('mw_cumulative_base_after', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', 'month', name='uq_payslip_emp_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payslips')
    # ### end Alembic commands ###
