"""add legal_name to companies

Revision ID: c192902f1ccf
Revises: 8e59d5d9b5d4
Create Date: 2026-06-09 14:12:58.567486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c192902f1ccf'
down_revision: Union[str, Sequence[str], None] = '8e59d5d9b5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('legal_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'legal_name')
    # ### end Alembic commands ###
